title: Jordan Waldroop # your name (or website title) here
logo: "/images/thumbnail.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Business Analytics
  _Security Analytics Track_
  <br>
  CU Boulder - May 2021
  <br><br>
  BS History
  Minor - Political Science
  <br>
  Western Carolina University - May 2020
# <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
